[project]
name = "vedana"
version = "2025.08.15-dev.17"
description = "Vedana"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "alembic>=1.16.4",
    "jims-core",
    "vedana-tg",
    "vedana-gradio",
    "vedana-etl",
    "vedana-eval",
]

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
namespace_packages = true
enable_incomplete_feature = ["NewGenericSyntax"]

[tool.ruff]
line-length = 120

[tool.uv.sources]
jims-core = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "memray>=1.18.0",
    "mypy>=1.16.1",
    "py-spy>=0.4.1",
    "ruff>=0.12.2",
    "types-requests>=2.32.4.20250611",
]
