[project]
name = "vedana"
version = "0.5.0"
description = "Semantic Graph RAG App"
readme = "README.md"
requires-python = ">=3.12"

[tool.uv.sources]
vedana-core = { workspace = true }
vedana-etl = { workspace = true }
vedana-tg = { workspace = true }
vedana-api = { workspace = true }
vedana-gradio = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
namespace_packages = true
enable_incomplete_feature = ["NewGenericSyntax"]

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.2",
]
