x-app-common: &app-common
  build:
    context: ../../
    dockerfile: apps/vedana/Dockerfile
  volumes:
    - ./data:/app/vedana/data
  environment:
    DB_CONN_URI: "postgresql://postgres:postgres@db:5432"
    JIMS_DB_CONN_URI: "postgresql://postgres:postgres@db:5432"
    CONFIG_PLANE_DB_CONN_URI: "postgresql://postgres:postgres@db:5432"
    MEMGRAPH_URI: "bolt://memgraph:7687"
  env_file:
    - .env
  depends_on:
    - memgraph
    - db

services:
  db-migrate:
    <<: *app-common
    command: uv run alembic upgrade head
    working_dir: /app/apps/vedana
    depends_on:
      db:
        condition: service_healthy

  app:
    <<: *app-common
    ports:
      - "3002:3000"
      - "8000:8000"
    command: uv run reflex run
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      memgraph:
        condition: service_started
      db:
        condition: service_healthy

  # tg:
  #   <<: *app-common
  #   command: uv run python -m vedana_tg.tg_app
  #   depends_on:
  #     db-migrate:
  #       condition: service_completed_successfully
  #     memgraph:
  #       condition: service_started
  #     db:
  #       condition: service_healthy

  # jims-backoffice:
  #   <<: *app-common
  #   command: uv run jims-backoffice
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db-migrate:
  #       condition: service_completed_successfully

  memgraph:
    image: memgraph/memgraph-mage
    ports:
      - 7687:7687
      - 7444:7444
    volumes:
      - mg_graph:/var/lib/memgraph
    env_file: .env
    restart: always
    command:
      [
        '--telemetry-enabled=false',
        '--storage-mode=IN_MEMORY_ANALYTICAL',
      ]

  memgraph-lab:
    image: memgraph/lab
    ports:
      - 3000:3000
    depends_on:
      - memgraph

  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mg_graph:
  postgres_data:
