[project]
name = "vedana-tg"
version = "0.5.0"
description = "Vedana Telegram interface"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "jims-core>=0.1.0",
    "jims-telegram>=0.1.0",
    "sqlalchemy>=2.0.41",
]

[tool.uv.sources]
jims-telegram = { path = "../../../jims/packages/jims-telegram/", editable = true }
jims-core = { path = "../../../jims/packages/jims-core/", editable = true }

[tool.mypy]
plugins = ['pydantic.mypy']

[tool.ruff]
line-length = 120
