[project]
name = "vedana-tg"
version = "0.1.0"
description = "Telegram UI for Vedana"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jims-telegram>=0.1.1",
    "vedana-core>=0.5.0",
]

[tool.uv.sources]
jims-telegram = { path = "../../../jims/packages/jims-telegram/", editable = true }
jims-core = { path = "../../../jims/packages/jims-core/", editable = true }
vedana-core = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.11.1",
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "mypy>=1.15.0",
    "python-dotenv>=1.1.0",
    "pytest>=8.4.0",
    "types-requests>=2.32.4.20250611",
    "pandas-stubs>=2.3.0.250703",
]

[tool.ruff]
line-length = 120
