[project]
name = "vedana-gradio"
version = "0.1.0"
description = "Gradio UI for Vedana"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio",
    "vedana-core>=0.5.0",
    "prometheus-client>=0.22.0",
    "grist-api>=0.1.1",
    "neo4j>=5.28.1",
    "openai>=1.75.0",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.9.1",
    "sqlalchemy>=2.0.41",
    "jims-core>=0.1.0",
    "jims-tui>=0.1.0",
    "jims-backoffice>=0.1.0",
    "alembic>=1.13.0",
    "asyncpg>=0.29.0",
    "aiogram>=3.0.0",
    "aiosqlite>=0.21.0",
    "aiohttp>=3.11.18",
    "sentry-sdk[fastapi,opentelemetry]>=2.32.0",
]

[tool.sources]
jims-core = { path = "../../../jims/packages/jims-core/", editable = true }
vedana-core = { workspace = true }

[tool.mypy]
plugins = ['pydantic.mypy']

[dependency-groups]
dev = [
    "ruff>=0.11.1",
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "mypy>=1.15.0",
    "python-dotenv>=1.1.0",
    "pytest>=8.4.0",
    "types-requests>=2.32.4.20250611",
    "pandas-stubs>=2.3.0.250703",
]

[tool.ruff]
line-length = 120
