persistentVolumeClaim:
  storageSize: ${size}

memgraphConfig:
- "--also-log-to-stderr=true"
%{ for value in memgraph_config ~}
- "${value}"
%{ endfor }

secrets:
  enabled: true
  name: ${secrets_name}

resources:
  requests:
    cpu: ${resources.requests.cpu}
    memory: ${resources.requests.memory}
  limits:
    cpu: ${resources.limits.cpu}
    memory: ${resources.limits.memory}